### PR TITLE
Expanding type system for generic types

### PR DESCRIPTION
**Pull request by jasonwoods-7**
PR for #10

### CODE REVIEW

**Comment by jasonwoods-7** [comment]
Oh, just realized that I haven't updated the README.md yet.  I'll try to get a check-in for that in the next few days.

Let me know if you have any comments or concerns about this PR in the meantime.

**Comment by jasonwoods-7** [comment]
Ok, that should finish up my check-ins for this PR.

**Comment by jasonwoods-7** [comment]
After doing some more testing, I found an issue with fields in generic types.

I'm writing more unit tests to make sure the solution I have is right.

**Comment by jasonwoods-7** [comment]
Ok, I think that'll fix everything up.

Let me know if you see any more issues.

**Comment by SimonCropp** [comment]
awesome work. i will ship it now

**Pull request merged**
